version: "3.7"

services:
  web:
    build:
      args:
        user: dev1
        uid: ${USER_ID}
      context:
        docker/web
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./web/:/var/www
    networks:
      - laravelwp

  node:
    image: node:14.11.0-alpine3.11
    command: npm install
    working_dir: /app
    volumes:
      - ./web/:/app
    networks:
      - laravelwp

  isocket:
    build:
      context: socket
    networks:
      - laravelwp
    restart: unless-stopped
    volumes:
      - ./socket/:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    ports:
      - ${DB_EXPOSE_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - mysql-vol:/var/lib/mysql
    networks:
      - laravelwp

  nginx:
    image: nginx:1.19.1-alpine
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
      - ${WEBSOCKET_PORT}:1357
    volumes:
      - ./web/:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravelwp

volumes:
  mysql-vol:
    driver: local

networks:
  laravelwp:
    driver: bridge